stages:
  - deploy

deploy web:
  stage: deploy
  image: wilson208/circleci-awscli:node
  script:
  - npm ci
  - npm run lint
  - npm run build
  - aws s3 rm s3://pagr.wilsonmccoubrey.com --recursive
  - aws s3 cp ./build/index.html s3://pagr.wilsonmccoubrey.com/ --cache-control max-age=0
  - aws s3 cp --recursive ./build s3://pagr.wilsonmccoubrey.com/ --cache-control max-age=2592000 --exclude index.html

  environment:
    name: Web
    url: https://pagr.wilsonmccoubrey.com/
